name: Continous Integration

on:
  push:
    branches: [ master ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
  
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    
    - name: Get tag info
      id: tagInfo
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=shaShort::$(git rev-parse --short HEAD)"
      
    - name: Build the Docker image 
      run: |
        cd application
        sh ./mvnw spring-boot:build-image
      
    - name: Docker Login
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      
    - name: Docker Image Tagging and Push
      run: |
        docker tag alehnert/gitops-evaluation-spring-boot-example $DOCKER_USER/$REPO_NAME:${{ steps.tagInfo.outputs.date }}-${{ steps.tagInfo.outputs.shaShort }}
        docker push $DOCKER_USER/$REPO_NAME:${{ steps.tagInfo.outputs.date }}-${{ steps.tagInfo.outputs.shaShort }}
